module.exports = {
  APP_TITLE: '%APP_TITLE%',
  APP_PASSWORD: '%APP_PASSWORD%',
  INSECURE_GMAIL_USERNAME: '%INSECURE_GMAIL_USERNAME%',
  INSECURE_GMAIL_PASSWORD: '%INSECURE_GMAIL_PASSWORD%',
  PSQL_URI: 'postgres://%SCHEMA%_postgraphql:%APP_PASSWORD%@%HOST%:%PORT%/%DB_NAME%',
  PSQL_ADMIN_URI: 'postgres://%ADMIN_USERNAME%:%ADMIN_PASSWORD%@%HOST%:%PORT%/%DB_NAME%',
  PSQL_DEFAULT_ROLE: '%SCHEMA%_anonymous',
  PSQL_SECRET: '%SECRET%',
  PSQL_SCHEMA: '%SCHEMA%',
}
