module.exports = {
  APP_TITLE: '%APP_TITLE%',
  APP_PASSWORD: '%APP_PASSWORD%',
  INSECURE_GMAIL_USERNAME: '%INSECURE_GMAIL_USERNAME%',
  INSECURE_GMAIL_PASSWORD: '%INSECURE_GMAIL_PASSWORD%',
  PSQL_URI: 'postgres://%PSQL_SCHEMA%_postgraphql:%APP_PASSWORD%@%HOST%:%PORT%/%DB_NAME%',
  PSQL_ADMIN_URI: 'postgres://%ADMIN_USERNAME%:%ADMIN_PASSWORD%@%HOST%:%PORT%/%DB_NAME%',
  PSQL_DEFAULT_ROLE: '%PSQL_SCHEMA%_anonymous',
  PSQL_SECRET: '%PSQL_SECRET%',
  PSQL_SCHEMA: '%PSQL_SCHEMA%',
}
