/* ModuleBuilder
  Index file autogenerated by ModuleBuilder
  Remove these lines or add custom file to override builder
*/

import simpleMailClient from './simpleMailClient.js'

export default {
  simpleMailClient,
}