/* ModuleBuilder
  Index file autogenerated by ModuleBuilder
  Remove these lines or add custom file to override builder
*/

import staticPlugin from './staticPlugin'

export default {
  staticPlugin,
}