/* ModuleBuilder
  Index file autogenerated by ModuleBuilder
  Remove these lines or add custom file to override builder
*/

import CalendarCard from './CalendarCard.vue'
import Card from './Card.vue'
import Clutch from './Clutch.vue'
import Comment from './Comment.vue'
import ContactCard from './ContactCard.vue'
import JumboTron from './JumboTron.vue'
import ProgressBar from './ProgressBar.vue'
import Spinner from './Spinner.vue'
import TopNav from './TopNav.vue'

export default {
  CalendarCard,
  Card,
  Clutch,
  Comment,
  ContactCard,
  JumboTron,
  ProgressBar,
  Spinner,
  TopNav,
}