/* ModuleBuilder
  Index file autogenerated by ModuleBuilder
  Remove these lines or add custom file to override builder
*/

import About from './About.vue'
import Contact from './Contact.vue'
import Home from './Home.vue'
import Login from './Login.vue'

export default {
  About,
  Contact,
  Home,
  Login,
}