/* ModuleBuilder
  Index file autogenerated by ModuleBuilder
  Remove these lines or add custom file to override builder
*/

import About from './About.vue'
import Board from './Board.vue'
import Calendar from './Calendar.vue'
import Forms from './Forms.vue'
import Home from './Home.vue'
import Join from './Join.vue'
import Login from './Login.vue'
import MissionStatement from './MissionStatement.vue'
import Programs from './Programs.vue'
import Units from './Units.vue'
import Welcome from './Welcome.vue'

export default {
  About,
  Board,
  Calendar,
  Forms,
  Home,
  Join,
  Login,
  MissionStatement,
  Programs,
  Units,
  Welcome,
}